[package]
name = "lunaria"
version = "0.0.0"
authors = [
    "Lunaria Contributors",
    "Jan David Nose <jandavid@playlunaria.com>",
]
edition = "2018"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

description = "A space-themed sandbox video game for programmers"
homepage = "https://playlunaria.com"
repository = "https://github.com/playlunaria/lunaria"
license = "MIT OR Apache-2.0"
keywords = [
    "game",
    "gamedev",
]
categories = [
    "games"
]

[[bench]]
name = "grpc_count"
harness = false

[[bin]]
name = "lunaria"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
lunaria-api = { version = "0.0.0", path = "../lunaria-api" }

bevy = "0.1.3"
chrono = "0.4.18"
tokio = { version = "0.2.22", features = ["macros", "rt-threaded"] }
tonic = "0.3.1"

[dev-dependencies]
criterion = "0.3.3"
