---
name: Preview

"on":
  schedule:
    - cron: "0 0 * * *"

jobs:
  preview:
    name: Preview
    strategy:
      matrix:
        channel:
          - beta
          - nightly
        os:
          - macos
          - windows
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.channel }}-cargo-v1-${{ hashFiles('Cargo.lock') }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
          override: true
          components: rustfmt

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

  ubuntu:
    name: Preview (ubuntu)
    strategy:
      matrix:
        channel:
          - beta
          - nightly
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          alsa \
          libasound2-dev \
          libudev-dev

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.channel }}-cargo-v1-${{ hashFiles('Cargo.lock') }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
          override: true
          components: rustfmt

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
